// INSERIR UM ELEMENTO NO DOM
let message = `<p class="message" style="font: 24px monospace; text-align: center;">This message was generated by JS!</p>`;
document.querySelector("body").insertAdjacentHTML('afterend', message);

// ENCONTRAR A LISTA PELO SEU ID
let list = document.getElementById("players");
const players = ["Pele", "Maradona", "Ronaldo"];
// INSERINDO OS JOGADORES NA LISTA
players.forEach((player) => {
  list.insertAdjacentHTML("beforeend", `<li>${player}</li>`);
})

// PEGAR O TEXTO DA CLASSE '.red' DA LISTA STAR WARS
let starWars = document.getElementById("star-wars")
starWars.querySelector(".red").innerText;

// MOSTRA NO TERMINAL, TODOS OS PAISES VENCEDORES
let fifaWinners = document.querySelectorAll("#fifa-wins li")
fifaWinners.forEach((country) => {
    console.log(country.innerText)
})

// INSERE MAIS UM PAIS NA LISTA DE PAISES VENCEDORES
document.getElementById("fifa-wins").insertAdjacentHTML('beforeend', "<li>France (2 wins)</li>")

// REMOVEMOS O PAIS QUE CONTEM O TEXTO "Argentina (3 wins)"
fifaWinners.forEach((country) => {
    if (country.innerText === "Argentina (3 wins)")
    {
        country.remove()
    }
})

// TROCANDO A COR DO ESTILO DO TEXTO
let element = document.querySelector(".message");
element.style.color = 'red';

// console.dir MOSTRA QUAIS SÃO OS ATTR DE UM ELEMENTO HTML
//console.dir(element.attributes)

// ESCONDER A VISUALIZAÇÃO DO ELEMENTO NA TELA 
element.style.display = "none";

// MOSTRAR O ELEMENTO NA TELA
element.style.display = "";

// SELECIONANDO O BOTAO
let button = document.getElementById("btn");

// INSERINDO A CLASSE DE BORDA QUANDO O BOTAO É CLICADO
button.addEventListener('click', () => {
    // if button.classList.contains("active") {
    //     button.classList.remove("active")
    // }
    button.classList.toggle("active")
})

// LENDO OS VALORES DO INPUT
let input = document.querySelector("input")
input.value = "gabriel@gmail.com"
console.log(input.value);

// TROCANDO O TEXTO DO LINK
let link = document.querySelector("#home");
link.innerText = "<strong>Obrigado por clicar!</strong>"
link.innerHTML = "Le Wagon <strong>rocks</strong>!";
// MOSTRANDO NO CONSOLE QUAL O VALOR DA URL A SER REDIRECIONADO
console.log(link.attributes.href.value);

// MOSTRANDO NO CONSOLE TODOS OS DATASETS DEFINIDOS ANTERIORMENTE
let pais = document.querySelector("#fifa-wins li")
console.log(pais.dataset.id)
console.log(pais.dataset.filter)

// ADICIONANDO EVENTO DE CLIQUE EM CADA UMA DAS FOTOS INDIVIDUALMENTE
let photos = document.querySelectorAll("img")
photos.forEach((photo) => 
    photo.addEventListener('click', () => {
    photo.classList.toggle("radius");
  })
)


